# -*- coding: utf-8 -*-
"""GroupProjectMIS315.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YG-8N4PpRFgvn1ho6-yV_LWcZRfJVq8C

# Yeni Bölüm
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

from numpy import cov
from numpy.random import randn
from numpy.random import seed
from numpy import mean
from numpy import std
import joblib
import sys

from scipy.stats import chi2_contingency

import time

sd = pd.read_csv('/911.csv')

#info about dataset
sd.info()
#mean,media,mode

print('the mean ıs')
sd.mean()
sd.median()
sd.mode()

#Variance
sd.var()
sd.std()

#mean

print('the mean is')
sd.mean()

#median
sd.median()

#mode
sd.mode()

#variance
sd.var()

#standard deviation
sd.std()

print(sd.quantile([.25, .5,.75]))

#boxplot
import matplotlib.pyplot as plt
fig = plt.figure(figsize =(20, 25))
plt.boxplot(sd.lat)
plt.show()

#scatter plot for latitude and longitude
import seaborn as sns
a=sd.lat


sd.lat=pd.to_numeric(sd.lat)
ss=sd[['lat','lng']]
sns.boxplot(data=ss,x='lat',y='lng')

plt.show()



sd.hist()

import numpy as np

#binning
sd['new_bin'] = pd.qcut(sd['lat'], q=3)
sd

np.linspace(0, 1, 10)

import numpy as np
from scipy.stats import chi2_contingency
obs = np.array([[5, 5, 6], [5, 5, 5]])
chi2_contingency(obs)

#PCA
import pandas as pd
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
# load dataset into Pandas DataFrame
df = pd.read_csv(url, names=['zip','lat','lng','desc','title'])
df

from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_sd

sd = load_sd()
X = sd.lat
y = sd.lng
knn = KNeighborsClassifier(n_neighbors=4)

import joblib
import sys
sys.modules['sklearn.externals.joblib'] = joblib
from mlxtend.feature_selection import SequentialFeatureSelector as SFS

sfs1 = SFS(knn,
           k_features=3,
           forward=True,
           floating=False,
           verbose=2,
           scoring='accuracy',
           cv=0)

sfs1 = sfs1.fit(X, y)

feature_names = ('zip', 'lat', 'lng', 'desc')
sfs1 = sfs1.fit(X, y, custom_feature_names=feature_names)
sfs1.subsets_

sfs1.k_feature_idx_

sfs1.k_feature_names_

sfs1.k_score_

#Tree induction
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

X, y = make_classification(
    n_samples=1000,
    n_features=10,
    n_informative=3,
    n_redundant=0,
    n_repeated=0,
    n_classes=2,
    random_state=0,
    shuffle=False,
)
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=42)

from sklearn.ensemble import RandomForestClassifier

feature_names = [f"feature {i}" for i in range(X.shape[1])]
forest = RandomForestClassifier(random_state=0)
forest.fit(X_train, y_train)

import time
import numpy as np

start_time = time.time()
importances = forest.feature_importances_
std = np.std([tree.feature_importances_ for tree in forest.estimators_], axis=0)
elapsed_time = time.time() - start_time

print(f"Elapsed time to compute the importances: {elapsed_time:.3f} seconds")

import pandas as pd

forest_importances = pd.Series(importances, index=feature_names)

fig, ax = plt.subplots()
forest_importances.plot.bar(yerr=std, ax=ax)
ax.set_title("Feature importances using MDI")
ax.set_ylabel("Mean decrease in impurity")
fig.tight_layout()

#sorting using the title of emergencıes
#we elıminated the null sets with no titles
sd.sort_values("title", inplace=True)
sd.info()

ltd = 37.370000
zmean= 19237.670750
zstd= 329.286946
zscores = [ltd - zmean / zstd]

print(zscores)

# Commented out IPython magic to ensure Python compatibility.
#Import the libraries
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # for data visualization
import seaborn as sns # for statistical data visualization
# %matplotlib inline
import os
for dirname, _, filenames in os.walk('/911.csv'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import warnings

warnings.filterwarnings('ignore')

#Import the dataset
data = '/911.csv'

sd = pd.read_csv(data)
sd.info()
sd.columns

# import SVC classifier
from sklearn.svm import SVC


# import metrics to compute accuracy
from sklearn.metrics import accuracy_score
# instantiate classifier with default hyperparameters
svc=SVC()


# fit classifier to training set
svc.fit(X_train,y_train)


# make predictions on test set
y_pred=svc.predict(X_test)

print('Model accuracy score with default hyperparameters: {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

# """**kNN SciKit**"""
from sklearn.neighbors import KNeighborsRegressor
knn_model = KNeighborsRegressor(n_neighbors=3)

knn_model.fit(X_train, y_train)

from sklearn.metrics import mean_squared_error
from math import sqrt
train_preds = knn_model.predict(X_train)
mse = mean_squared_error(y_train, train_preds)
rmse = sqrt(mse)
rmse

test_preds = knn_model.predict(X_test)
mse = mean_squared_error(y_test, test_preds)
rmse = sqrt(mse)
rmse

from sklearn.metrics import confusion_matrix
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

#Scaling the features
cols = X_train.columns

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

X_train = pd.DataFrame(X_train, columns=[cols])

X_test = pd.DataFrame(X_test, columns=[cols])

X_train.describe()

# import SVC classifier
from sklearn.svm import SVC


# import metrics to compute accuracy
from sklearn.metrics import accuracy_score


# instantiate classifier with default hyperparameters
svc=SVC()


# fit classifier to training set
svc.fit(X_train,y_train)


# make predictions on test set
y_pred=svc.predict(X_test)

print('Model accuracy score with default hyperparameters: {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

#nstantiate classifier with rbf kernel and C=100
svc=SVC(C=100.0)


# fit classifier to training set
svc.fit(X_train,y_train)


# make predictions on test set
y_pred=svc.predict(X_test)


# compute and print accuracy score
print('Model accuracy score with rbf kernel and C=100.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

# instantiate classifier with rbf kernel and C=1000
svc=SVC(C=1000.0)


# fit classifier to training set
svc.fit(X_train,y_train)


# make predictions on test set
y_pred=svc.predict(X_test)


# compute and print accuracy score
print('Model accuracy score with rbf kernel and C=1000.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

#With linear kernel
# instantiate classifier with linear kernel and C=1.0
linear_svc=SVC(kernel='linear', C=1.0)


# fit classifier to training set
linear_svc.fit(X_train,y_train)


# make predictions on test set
y_pred_test=linear_svc.predict(X_test)


# compute and print accuracy score
print('Model accuracy score with linear kernel and C=1.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred_test)))

print('Training set score: {:.4f}'.format(linear_svc.score(X_train, y_train)))

print('Test set score: {:.4f}'.format(linear_svc.score(X_test, y_test)))